"""Repository for persisting and querying XAI post-hoc explanations."""

from typing import List, Optional, Sequence
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.module8_database.models.explanation import TransactionExplanation
from src.module8_database.repositories.base_repository import BaseRepository


class ExplanationRepository(BaseRepository[TransactionExplanation]):
    """Data access repository for TransactionExplanation records."""

    def __init__(self):
        super().__init__(TransactionExplanation)

    async def get_latest_by_tx(
        self,
        session: AsyncSession,
        tx_id: str,
    ) -> Optional[TransactionExplanation]:
        """Retrieves the most recent explanation generated for a given transaction."""
        query = (
            select(TransactionExplanation)
            .where(TransactionExplanation.tx_id == tx_id)
            .order_by(TransactionExplanation.created_at.desc())
            .limit(1)
        )
        result = await session.execute(query)
        return result.scalars().first()

    async def get_by_model_version(
        self,
        session: AsyncSession,
        model_version: str,
        limit: int = 100,
    ) -> Sequence[TransactionExplanation]:
        """Retrieves explanation artifacts generated by a specific model version."""
        query = (
            select(TransactionExplanation)
            .where(TransactionExplanation.model_version == model_version)
            .order_by(TransactionExplanation.created_at.desc())
            .limit(limit)
        )
        result = await session.execute(query)
        return result.scalars().all()
